(require '2.02-segment&point)

(define (make-rect p1 p2 p3 p4)
  (list p1 p2 p3 p4))
(define (vertice-1 rect)
  (car rect))
(define (vertice-2 rect)
  (cadr rect))
(define (vertice-3 rect)
  (caddr rect))
(define (vertice-4 rect)
  (cadddr rect))

(define (distance p1 p2)
  (define (sqr-diff i1 i2)
    (square (- i1 i2)))
  (sqrt (+ (sqr-diff (point-x p1)
                     (point-x p2))
           (sqr-diff (point-y p1)
                     (point-y p2)))))
(define (rect-area rect)
  (let ((p2 (vertice-2 rect)))
    (* (distance (vertice-1 rect) p2)
       (distance (vertice-3 rect) p2))))