######################################################################
# Automatically generated by qmake (3.1) Tue Apr 14 13:44:02 2020
######################################################################

TEMPLATE = subdirs
SUBDIRS = gui-bitstream \
          unitTests

# gui.depends = serializelib
