######################################################################
# Automatically generated by qmake (3.1) Thu Apr 16 12:34:23 2020
######################################################################

all:
    g++ -lpthread test.cpp ../gui-bitstream/BitSocket.cpp -o unitTests