(define (fib n)
  (cond ((= n 0) 0)
        ((= n 1) 1)
        (else (+ (fib (- n 1))
            (fib (- n 2))))))

(define (fib n)
  (define (aux a b n)
    (if (= n 0)
        a
        (aux b (+ a b) (- n 1))))
  (aux 0 1 n)
  ;; (cond ((= n 0) 0)
  ;;       ((= n 1) 1)
  ;;       (else (+ (fib (- n 1))
  ;;           (fib (- n 2)))))
  )